### ISSUE TITLE
集成OverFlow，调用uploadVoice接口报错

### ISSUE THREAD

**Issue by pikad520** [project-tRNA/overflow-shamrock-ext#1]
调用接口报错，如下

2024-02-29 11:56:05 E/MAH Access: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 7: Encountered an unknown key 'status' at path: $
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: {
    "status": "failed",
    "retcode": 20002,
    "data": {
        "url": "/upload_file",
        "error": "Content-Type header is required for multipart processing"
    }
}
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 7: Encountered an unknown key 'status' at path: $
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
JSON input: {
    "status": "failed",
    "retcode": 20002,
    "data": {
        "url": "/upload_file",
        "error": "Content-Type header is required for multipart processing"
    }
}
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
        at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:579)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:251)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:237)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:172)
        at overflow-shamrock-ext-0.1.0.mirai2.jar//top.mrxiaom.overflow.shamrock.ShamrockFileService$ShamrockFile$$serializer.deserialize(ShamrockFileService.kt:30)
        at overflow-shamrock-ext-0.1.0.mirai2.jar//top.mrxiaom.overflow.shamrock.ShamrockFileService$ShamrockFile$$serializer.deserialize(ShamrockFileService.kt:30)
        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:97)
        at overflow-shamrock-ext-0.1.0.mirai2.jar//top.mrxiaom.overflow.shamrock.ShamrockFileService.upload(ShamrockFileService.kt:26)
        at top.mrxiaom.overflow.internal.contact.GroupWrapper.uploadAudio(GroupWrapper.kt:202)
        at mirai-api-http-2.9.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.internal.action.MessageKt.onUploadVoice(message.kt:210)
        at mirai-api-http-2.9.1.mirai2.jar//net.mamoe.mirai.api.http.adapter.http.router.MessageKt$messageRouter$1$invoke$$inlined$httpAuthedMultiPart$2$1.invokeSuspend(dsl.kt:209)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

**Comment by pikad520** [comment]
content-type是apifox自动生成的，如果手动添加这个头，会报一个和boundary相关的错：Failed to parse multipart: Content-Type's boundary parameter is missing

**Comment by MrXiaoM** [comment]
0.1.1 已修复

**Comment by pikad520** [comment]
> 0.1.1 已修复收到，明天去公司试试。目前我已经改用shamrock+自己实现的简陋终端替代了mirai😂
